### ISSUE TITLE
Failed to save session

### ISSUE THREAD

**Issue by dbaje** [lukaszraczylo/traefikoidc#15]
Cookie size is limited to 4096. The fact that both access and refresh tokens are stored along with other things, it's easy to run into issues.

Would it be possible to either look to increase or see another storage option?

I tested at my end, default tokens JWT from casdoor and I need to change signature and only get the non empty data to be able to fit. I am afraid that eventually we are going to run into the size issue again.

**Comment by mofr93** [comment]
We have run into this issue because we have many groups. Any way we can increase this value in the middleware?

**Comment by lukaszraczylo** [comment]
Hi both, I'm trying to figure out the best way to approach it at the moment, so anytime soon, hopefully :)

**Comment by lukaszraczylo** [comment]
@mofr93 & @dbaje try the v0.4.0 - it uses different cookies for the session management so unless you treat the jwt token as a database, everything should stick to the limits :)

**Comment by mofr93** [comment]
@lukaszraczylo Thanks for the quick reply! I will test and report back what i find asap :)

**Comment by mofr93** [comment]
Hi @lukaszraczylo. So i have tested it and it does look a lot better with the cookie size.

However because my organization has a lot of groups I still run into

```Failed to save session: failed to save access token session: {%!s(int=1) the value is too long <nil>}: 7968```

I think I will limit the amount of emitted groups on my end so it's all good 👍 

Another thing. Do we not set `X-User-Groups` or `X-User-roles` header anymore? Looks like it was removed. Anyway to get it back? :) 

And thanks again for the help!

**Comment by lukaszraczylo** [comment]
Let me see what can be done with that :) I may need to introduce separate, non-cookie storage for the sessions as from what it looks like there's no chance we can pack it all up into the cookie limit

**Comment by lukaszraczylo** [comment]
[v0.4.1](https://github.com/lukaszraczylo/traefikoidc/releases/tag/v0.4.1) brings back the headers. Going to check the cookie size workaround :)

**Comment by lukaszraczylo** [comment]
@mofr93 - the v0.4.2 should bring the token chunking, bypassing the limits on the cookies. Could you check it?

**Comment by mofr93** [comment]
@lukaszraczylo Hello. I tested it and it works well with the cookie chunking. I now see all groups in the X-User-Group header  👍

**Comment by lukaszraczylo** [comment]
Phew! :) Thank you for coming back to me, happy I was able to sort it out with single PR :)

**Comment by mofr93** [comment]
Thanks for the help @lukaszraczylo :) 

This might be more related to Azure OIDC and not the middleware. But having a long id_token with many groups, like mine. makes the Azure logout endpoint not work. 

`AADSTS90015: Requested query string is too long.`

There is some talk about it here: https://github.com/keycloak/keycloak/issues/24794
